### ISSUE TITLE
quests and areas not access able

### ISSUE THREAD

**Issue by hnorri** [Median-XL/Issue-Tracker#17]
I seem to have some problems with decard cain quest no scroll coming out of tree. stony tomb act 2 can enter had trouble getting out had to portal out could not get to treasure room in stony tomb and halls of the dead level 2 inaccessible cheers

**Comment by GavinK88** [comment]
You must rescue Cain before entering act 2. If you enter act 2 in the same game as not having rescued Cain, it cannot be completed and a new game must be made, this is vanilla d2 behavior and won't be patched due to the potential issues that could arise from it. As for Treasure Vault and Halls of the Dead, these areas serve no purpose until Hell Difficulty where Island of the Sunless Sea and Tran Athulua can be accessed respectively.
